# Generated by Django 5.2.7 on 2025-10-02 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 2, 14, 27, 5, 894304, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
