# Generated by Django 5.2.7 on 2025-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0006_offer_offerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium')], default='basic', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='testoffer', max_length=255),
            preserve_default=False,
        ),
    ]
